include_recipe 'apt::default'
include_recipe 'capistrano-ruby::user'
include_recipe 'capistrano-ruby::ssh'
include_recipe 'capistrano-ruby::rvm'
include_recipe 'nodejs::default'
include_recipe 'capistrano-ruby::chown'
include_recipe 'capistrano-ruby::mysql-server'
include_recipe 'capistrano-ruby::database-mysql'
