---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[chef-solo-search::default]
      - recipe[capistrano-ruby-test::default]
      - recipe[rvm::vagrant]
    attributes:
      rvm:
        vagrant:
          system_chef_solo: /opt/chef/bin/chef-solo
