---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-16.04

suites:
  - name: web-app-role
    run_list:
      - recipe[apt::default]
      - recipe[chef-solo-search::default]
      - recipe[capistrano-ruby::web-app-role]
