name             'capistrano-ruby'
maintainer       'Adam Krone'
maintainer_email 'krone.adam@gmail.com'
license          'apachev2'
description      'Installs/Configures a system for capistrano ruby app deployment'
long_description 'Installs/Configures a system for capistrano ruby app deployment'
version          '0.1.0'

depends 'apt'
depends 'users'
depends 'sudo'
depends 'ssh-hardening'
depends 'rvm'
depends 'nodejs'
depends 'apache2'
depends 'postgresql'
depends 'database'
